#pragma once
#include "DuckModule.h"
#include "ECharacterAssetBranchType.generated.h"

UENUM(BlueprintType)
enum class ECharacterAssetBranchType : uint8 {
    ALWAYS,
    ELSE,
    HIT,
    HIT_CHARA_ID,
    GUARD,
    SWING,
    HIT_ATEMI,
    BODY_PUSH,
    POSE_STATUS,
    ACTION_STATUS,
    ACTION_CATEGORY,
    ACTION_ID,
    HEIGHT,
    LANDING,
    WALL_F,
    WALL_B,
    OBSTACLE,
    OBSTACLE_Y,
    SIDE,
    RANGE,
    STEER,
    TRIGGER,
    COMMAND,
    ARMOR,
    ATEMI,
    TARGET_LOSS,
    CHARA_ID,
    PARTNER_NO,
    FIGHT_STYLE,
    UNIQUE_PARAM,
    UNIQUE_TIMER,
    LOOP_COUNT,
    VITAL,
    GEM_GAUGE,
    GEM_KIND,
    FINISH,
    DURABILITY,
    GEM_SPACE,
    RANDOM,
    CATCH_F,
    CATCH_B,
    CATCH_N,
    HIT_CATCH,
    NEGATIVE_X,
    NEGATIVE_Y,
    AREA_PARENT,
    AREA_TARGET,
    AREA_RIVAL_TEAM,
    SHOT_HIT,
    SHOT_DAMAGE,
    SHOT_REFLECT,
    SHOT_HIT_COUNT_0,
};

