#pragma once
#include "DuckModule.h"
#include "EGameMode.generated.h"

UENUM(BlueprintType)
enum class EGameMode : uint8 {
    GAME_MODE_NONE,
    GAME_MODE_STORY,
    GAME_MODE_VERSUS_2P,
    GAME_MODE_VERSUS_CPU,
    GAME_MODE_RANKED_MATCH,
    GAME_MODE_PLAYER_MATCH,
    GAME_MODE_TRAINING,
    GAME_MODE_ARCADE,
    GAME_MODE_COLLECTION,
    GAME_MODE_MISSION,
    GAME_MODE_REPLAY,
    GAME_MODE_PROFILE_CARD,
    GAME_MODE_ROOKIE_LEAGUE,
    GAME_MODE_ONLINE_TRAINING,
    GAME_MODE_LOBBY,
    GAME_MODE_RANKING,
    GAME_MODE_TITLE,
    GAME_MODE_MAX UMETA(Hidden),
};

