#pragma once
#include "DuckModule.h"
#include "EPlayerType.generated.h"

UENUM(BlueprintType)
enum class EPlayerType : uint8 {
    COMMON,
    ULTRON,
    MEGA_MAN_X,
    GAMORA,
    JEDAH,
    THANOS,
    RYU,
    CAPTAIN_MARVEL,
    DANTE,
    IRONMAN,
    MORRIGAN,
    CAPTAIN_AMERICA,
    STRIDER_HIRYU,
    SPIDERMAN,
    CHUN_LI,
    HULK,
    FIREBLAND,
    MIGHTY_THOR,
    CHRIS,
    ROCKET_RACCOON,
    FRANK_WEST,
    DR_STRANGE,
    ZERO,
    NOVA,
    HAGGAR,
    GHOST_RIDER,
    NEMESIS,
    HAWKEYE,
    SPENCER,
    DORMAMMU,
    ARTHUR,
    HYPER_THANOS,
    SIGMA_ULTRON,
    OMEGA_ULTRON,
    VENOM,
    SIGMA,
    BLACK_PANTHER,
    WINTER_SOLDIER,
    BLACK_WIDOW,
    HUNTER,
    ULTRON_DRONE,
    X_GARDIEN,
    SYMBIOTE_SOLDIER,
    HUGE_SYMBIOTE,
    DAHREN_MOHRAN,
    GRAND_MASTER,
    MODOK,
    PLAYER_TYPE_NUM,
    UNKNOWN = 0xFE,
};

