#pragma once
#include "DuckModule.h"
#include "EStoryTextSpType.generated.h"

UENUM(BlueprintType)
enum class EStoryTextSpType : uint8 {
    TXT_SUPPLEMENTARY_STONE_50,
    TXT_SUPPLEMENTARY_STONE_100,
    TXT_SUPPLEMENTARY_HUGE_SWARM_PL028,
    TXT_SUPPLEMENTARY_FACE_2_ENEMY,
    TXT_SUPPLEMENTARY_PL020_COMMAND_2_STONE,
    TXT_SUPPLEMENTARY_VS_PL02C,
    TXT_SUPPLEMENTARY_VS_PL02E,
    TXT_SUPPLEMENTARY_SHIELD_GAUGE,
    TXT_SUPPLEMENTARY_PL016_POWER_UP,
    TXT_SUPPLEMENTARY_VS_PL02D,
    TXT_SUPPLEMENTARY_PL008_POWER_UP,
    TXT_SUPPLEMENTARY_STONE_CHANGE,
    TXT_SUPPLEMENTARY_RESTRAINT_PL008,
    TXT_SUPPLEMENTARY_INC_DAMAGE_NATURAL_ENEMY,
    TXT_SUPPLEMENTARY_MAX UMETA(Hidden),
};

