#pragma once
#include "DuckModule.h"
#include "EStoryExclusivRule.generated.h"

UENUM(BlueprintType)
enum class EStoryExclusivRule : uint8 {
    NONE,
    SCENE_0_B_1,
    SCENE_0_B_2,
    SCENE_1_B_1,
    SCENE_1_B_2,
    SCENE_1_C_1,
    SCENE_1_C_2,
    SCENE_3_F_1,
    SCENE_3_F_2,
    SCENE_3_F_3,
    SCENE_3_C_1,
    SCENE_3_C_2,
    SCENE_3_C_3,
    SCENE_3_C_4,
    SCENE_3_E_1,
    SCENE_3_E_2,
    SCENE_3_D_1,
    SCENE_3_D_2,
    SCENE_3_A_1,
    SCENE_3_A_2,
    SCENE_3_A_3,
    SCENE_3_G_1,
    SCENE_3_G_2,
    SCENE_3_G_3,
    SCENE_3_G_4,
    SCENE_0_A_1,
    SCENE_4_B_1,
    SCENE_4_C_1,
    SCENE_5_A_1,
    SCENE_5_A_2,
    SCENE_4_G_1,
    SCENE_4_G_2,
    SCENE_5_B_1,
    SCENE_5_B_2,
    SCENE_0_B_E_1,
    SCENE_0_B_E_2,
    SCENE_4_B_E_1,
    SCENE_4_B_E_2,
    SCENE_4_B_E_3,
    SCENE_4_B_E_4,
    SCENE_0_B_E_3,
};

