#pragma once
#include "DuckModule.h"
#include "ETravelOption.generated.h"

UENUM(BlueprintType)
enum class ETravelOption : uint8 {
    TRAVEL_OP_LOADING_ICON_OFF,
    TRAVEL_OP_WAIT_FADE_END,
    TRAVEL_OP_WAIT_LOAD_CMN_END,
    TRAVEL_OP_INPUT_DISABLE,
    TRAVEL_OP_DLC_CHECK,
    TRAVEL_OP_NO_REMOVE_TRANSITION_WIDGET,
    TRAVEL_OP_FINALIZE_STORY_AFTER_FADE,
    TRAVEL_OP_RESET_BY_INTERRUPT_TRAVEL,
    TRAVEL_OP_PRIORITY_HIGH,
    TRAVEL_OP_PRIORITY_CRITICAL,
    TRAVEL_OP_MAX UMETA(Hidden),
};

