#pragma once
#include "DuckModule.h"
#include "GameButtonType.generated.h"

UENUM(BlueprintType)
enum class GameButtonType : uint8 {
    UP,
    DOWN,
    LEFT,
    RIGHT,
    UP_RIGHT,
    UP_LEFT,
    DOWN_RIGHT,
    DOWN_LEFT,
    LStick_UP,
    LStick_DOWN,
    LStick_LEFT,
    LStick_RIGHT,
    LStick_UP_RIGHT,
    LStick_UP_LEFT,
    LStick_DOWN_RIGHT,
    LStick_DOWN_LEFT,
    RStick_UP,
    RStick_DOWN,
    RStick_LEFT,
    RStick_RIGHT,
    RStick_UP_RIGHT,
    RStick_UP_LEFT,
    RStick_DOWN_RIGHT,
    RStick_DOWN_LEFT,
    BtnLeft,
    BtnTop,
    BtnBottom,
    BtnRight,
    L1,
    R1,
    L2,
    R2,
    L3,
    R3,
    DECIDE,
    CANCEL,
    START,
    SELECT,
    BATTLE_MENU_OPEN,
    NUM,
    _Invalid,
};

